spring.application.name=demo-eni-ecole

#Connexion � la base de donn�es
spring.datasource.url=jdbc:sqlserver://localhost;databasename=DEMO_ENI_ECOLE;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

#D�tail des requ�tes pour le d�veloppement
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.messages.encoding=utf-8

# JWT
app.jwt.secret=5f683f313c302d2175757655323f6d6b3a58565737433e6c6a6b382054
